apiVersion: v1
kind:       Service
metadata: {
  name: #config.metadata.name + "-controller-manager-metrics-service"
  labels: #config.test-operator.metadata.labels & {
    {
    	"control-plane": "controller-manager"
    }
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "test-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}