apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRole
metadata: {
  name: #config.metadata.name + "-proxy-role"
  labels: #config.test-operator.metadata.labels & {
{
	rules: [{
		apiGroups: ["authentication.k8s.io"]
		resources: ["tokenreviews"]
		verbs: ["create"]
	}, {
		apiGroups: ["authorization.k8s.io"]
		resources: ["subjectaccessreviews"]
		verbs: ["create"]
	}]
}
---
apiVersion: rbac.authorization.k8s.io/v1
kind:       ClusterRoleBinding
metadata: {
  name: #config.metadata.name + "-proxy-rolebinding"
  labels: #config.test-operator.metadata.labels & {
{
	roleRef: {
		apiGroup: "rbac.authorization.k8s.io"
		kind:     "ClusterRole"
		name:     "#config.metadata.name + \"-proxy-role\""
	}
}
{
	subjects: [{
		kind:      "ServiceAccount"
		name:      "#config.metadata.name + \"-controller-manager\""
		namespace: "{{ .Release.Namespace }}"
	}]
}